import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';
import { ascent } from '@/api/client';

const ThemeContext = createContext();

export const translations = {
  en: {
    // Navigation
    portfolio: 'Portfolio',
    dashboard: 'Dashboard',
    expenses: 'Expenses',
    settings: 'Settings',
    menu: 'Menu',
    notes: 'Notes',
    notesDescription: 'Your personal notes and ideas',
    calendar: 'Calendar',
    googleCalendar: 'Google Calendar',
    connectCalendar: 'Connect Your Calendar',
    connectCalendarDesc: 'Connect your Google Calendar to view and manage your events directly from the app.',
    connectWithGoogle: 'Connect with Google',
    calendarConnected: 'Google Calendar connected!',
    calendarDisconnected: 'Calendar disconnected',
    calendarSessionExpired: 'Calendar session expired. Please reconnect.',
    reconnect: 'Reconnect',
    disconnect: 'Disconnect Calendar',
    newEvent: 'New Event',
    newTask: 'New Task',
    taskTitle: 'Task Title',
    taskTitlePlaceholder: 'Add task title',
    taskTitleRequired: 'Task title is required',
    taskCreated: 'Task created!',
    dueDate: 'Due Date',
    addNotes: 'Add notes',
    editEvent: 'Edit Event',
    eventTitle: 'Title',
    eventTitlePlaceholder: 'Add title',
    eventTitleRequired: 'Event title is required',
    eventCreated: 'Event created!',
    eventUpdated: 'Event updated!',
    eventDeleted: 'Event deleted!',
    startTime: 'Start',
    endTime: 'End',
    allDayEvent: 'All day event',
    allDay: 'All day',
    location: 'Location',
    addLocation: 'Add location',
    addDescription: 'Add description',
    noEventsToday: 'No events scheduled',
    today: 'Today',
    day: 'Day',
    week: 'Week',
    month: 'Month',
    calendarDescription: 'View and manage your Google Calendar events',
    newNote: 'New Note',
    editNote: 'Edit Note',
    noteTitle: 'Title',
    noteContent: 'Write your note...',
    noteColor: 'Color',
    noteCreated: 'Note created',
    noteUpdated: 'Note updated',
    noteDeleted: 'Note deleted',
    noteTitleOrContentRequired: 'Please add a title or content',
    searchNotes: 'Search notes...',
    noNotesYet: 'No notes yet',
    createFirstNote: 'Create your first note to get started',
    pinned: 'Pinned',
    others: 'Others',
    pin: 'Pin',
    unpin: 'Unpin',
    noContent: 'No content',
    tags: 'Tags',
    addTag: 'Add tag...',
    logout: 'Logout',
    sessionExpired: 'Session expired. Please log in again.',
    sessionExpiringSoon: 'Your session will expire in 1 minute due to inactivity.',
    ascend: 'Ascent',
    ascendTagline: 'Rise above your financial goals',
    
    // User Menu
    owner: 'Owner',
    sharedUser: 'Shared User',
    darkMode: 'Dark Mode',
    blurValues: 'Blur Values',
    user: 'User',
    
    // Common
    loading: 'Loading...',
    save: 'Save',
    create: 'Create',
    cancel: 'Cancel',
    created: 'Created',
    updated: 'Updated',
    delete: 'Delete',
    edit: 'Edit',
    duplicate: 'Duplicate',
    add: 'Add',
    close: 'Close',
    confirm: 'Confirm',
    search: 'Search',
    filter: 'Filter',
    clearFilters: 'Clear Filters',
    results: 'results',
    result: 'result',
    saving: 'Saving...',
    updating: 'Updating...',
    adding: 'Adding...',
    deleting: 'Deleting...',
    optional: 'Optional',
    confirmDelete: 'Confirm Delete',
    confirmDeletePosition: 'Are you sure you want to delete this position? This action cannot be undone.',
    confirmDeleteDayTrade: 'Are you sure you want to delete this day trade? This action cannot be undone.',
    confirmDeleteAllPositions: 'Are you sure you want to delete all positions for {symbol}? This action cannot be undone.',
    
    // Login/Register
    welcome: 'Welcome',
    signInToAccount: 'Sign in to your account or create a new one',
    orContinueWithEmail: 'or continue with email',
    login: 'Login',
    register: 'Register',
    signIn: 'Sign In',
    signingIn: 'Signing in...',
    creatingAccount: 'Creating account...',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    welcomeBack: 'Welcome back!',
    accountCreated: 'Account created successfully!',
    passwordsDoNotMatch: 'Passwords do not match',
    passwordMinLength: 'Password must be at least 6 characters',
    loginFailed: 'Login failed',
    registrationFailed: 'Registration failed',
    googleSignInFailed: 'Google sign-in failed',
    continueWithGoogle: 'Continue with Google',
    
    // Payment Methods
    paymentMethod: 'Payment Method',
    selectPaymentMethod: 'Select payment method',
    selectCard: 'Select Card',
    selectACard: 'Select a card',
    noCardsAvailable: 'No cards available - Add in Settings',
    card: 'Card',
    cash: 'Cash',
    transfer: 'Transfer',
    
    // Dashboard
    yourCompleteFinancialOverview: 'Your complete financial overview',
    customize: 'Customize',
    totalPortfolio: 'Total Portfolio',
    totalPnL: 'Total P&L',
    invested: 'Invested',
    savingsRate: 'Savings Rate',
    ofPortfolio: 'of portfolio',
    thisMonth: 'This month',
    portfolioValue: 'Portfolio Value',
    portfolioValueTrend: 'Portfolio Value Trend',
    last30Days: 'Last 30 days',
    netWorth: 'Net Worth',
    netWorthTrend: 'Net Worth Trend (30 Days)',
    allocationByAccountType: 'Allocation by Account Type',
    assetAllocation: 'Asset Allocation',
    performanceVsSP500: 'Performance vs S&P 500',
    yourPortfolio: 'Your Portfolio',
    sp500Benchmark: 'S&P 500 Benchmark',
    difference: 'Difference',
    outperforming: 'Outperforming',
    underperforming: 'Underperforming',
    financialGoals: 'Financial Goals',
    addGoal: 'Add Goal',
    noGoalsYet: 'No financial goals set yet',
    setYourFirstGoal: 'Set Your First Goal',
    accountSummary: 'Account Summary',
    noAccountsYet: 'No accounts yet. Create your first account to get started.',
    
    // Portfolio
    investmentAccounts: 'Investment Accounts',
    addAccount: 'Add Account',
    noAccountsCreateFirst: 'No accounts yet. Create your first investment account to start tracking your portfolio',
    totalValue: 'Total Value',
    totalPortfolioValue: 'Total Portfolio Value',
    totalReturn: 'Total Return',
    trackAndManageAccounts: 'Track and manage your investment accounts',
    createYourFirstAccount: 'Create Your First Account',
    noAccountsYetTitle: 'No accounts yet',
    accountTypeInvestment: 'Investment',
    accountTypeRetirement: 'Retirement',
    accountTypeIRA: 'IRA',
    accountTypePension: 'Pension',
    accountTypeSavings: 'Savings',
    accountTypeOther: 'Other',
    accountCreatedSuccessfully: 'Account created successfully!',
    failedToCreateAccount: 'Failed to create account',
    accountDeletedSuccessfully: 'Account deleted successfully!',
    failedToDeleteAccount: 'Failed to delete account',
    done: 'Done',
    
    // Success/Error Messages
    goalCreatedSuccessfully: 'Goal created successfully!',
    goalUpdatedSuccessfully: 'Goal updated successfully!',
    goalDeletedSuccessfully: 'Goal deleted successfully!',
    dashboardLayoutSaved: 'Dashboard layout saved!',
    transactionAddedSuccessfully: 'Transaction added successfully!',
    transactionUpdatedSuccessfully: 'Transaction updated successfully!',
    transactionDeletedSuccessfully: 'Transaction deleted successfully!',
    failedToAddTransaction: 'Failed to add transaction',
    failedToUpdateTransaction: 'Failed to update transaction',
    failedToDeleteTransaction: 'Failed to delete transaction',
    deleteTransaction: 'Delete Transaction',
    deleteTransactionConfirmation: 'Are you sure you want to delete this transaction? This action cannot be undone.',
    budgetCreatedSuccessfully: 'Budget created successfully!',
    budgetUpdatedSuccessfully: 'Budget updated successfully!',
    budgetDeletedSuccessfully: 'Budget deleted successfully!',
    failedToCreateBudget: 'Failed to create budget',
    failedToUpdateBudget: 'Failed to update budget',
    failedToDeleteBudget: 'Failed to delete budget',
    categoryCreatedSuccessfully: 'Category created successfully!',
    categoryDeletedSuccessfully: 'Category deleted successfully!',
    failedToCreateCategory: 'Failed to create category',
    failedToDeleteCategory: 'Failed to delete category',
    pleaseFillAllFields: 'Please fill in all fields',
    last4DigitsMustBe4: 'Last 4 digits must be exactly 4 numbers',
    
    // Expenses
    incomeExpenseTracking: 'Income & Expense Tracking',
    manageYourFinances: 'Manage your finances and track spending',
    addTransaction: 'Add Transaction',
    totalIncome: 'Total Income',
    totalExpenses: 'Total Expenses',
    netAmount: 'Net Amount',
    net: 'Net',
    expensesByCategory: 'Expenses by Category',
    expensesByPaymentMethod: 'Expenses by Payment Method',
    noPaymentMethodData: 'No payment method data',
    noDataAvailable: 'No data available',
    noPositionsYet: 'No positions yet',
    monthlyTrend: 'Monthly Trend',
    monthlyTrendLast6: 'Monthly Trend (Last 6 Months)',
    noTransactionsYet: 'No transactions yet',
    startTrackingFinances: 'Start tracking your finances by adding your first transaction',
    trackYourIncomeExpenses: 'Track your income and expenses',
    incomeThisMonth: 'Income (This Month)',
    expensesThisMonth: 'Expenses (This Month)',
    transactions: 'Transactions',
    searchTransactions: 'Search transactions...',
    noExpenseData: 'No expense data available',
    income: 'Income',
    expense: 'Expense',

    // Transaction Dialog
    editTransaction: 'Edit Transaction',
    duplicateTransaction: 'Duplicate Transaction',
    duplicateTransactionDescription: 'Create a copy of this transaction with today\'s date',
    addTransactionTitle: 'Add Transaction',
    updateTransactionDetails: 'Update transaction details',
    recordNewTransaction: 'Record a new income or expense transaction',
    date: 'Date',
    type: 'Type',
    category: 'Category',
    description: 'Description',
    amount: 'Amount',
    currency: 'Currency',
    relatedAccount: 'Related Account (Optional)',
    selectAccountOptional: 'Select an account (optional)',
    none: 'None',
    linkTransactionToAccount: 'Link this transaction to an investment account if applicable',
    updateTransaction: 'Update Transaction',
    dateRequired: 'Date is required',
    descriptionRequired: 'Description is required',
    amountGreaterThanZero: 'Amount must be greater than 0',
    descriptionPlaceholder: 'e.g., Grocery shopping at Whole Foods',

    // Transaction Filters
    filters: 'Filters',
    clear: 'Clear',
    last7Days: 'Last 7 Days',
    allTime: 'All Time',
    fromDate: 'From Date',
    toDate: 'To Date',
    allTypes: 'All Types',
    expensesOnly: 'Expenses Only',
    incomeOnly: 'Income Only',
    allCategories: 'All Categories',

    // Transaction List
    noTransactionsFound: 'No transactions found',
    addFirstTransactionOrAdjust: 'Add your first transaction or adjust your filters',

    // Categories
    foodDining: 'Food & Dining',
    groceries: 'Groceries',
    rentHousing: 'Rent & Housing',
    transportation: 'Transportation',
    healthcare: 'Healthcare',
    entertainment: 'Entertainment',
    shopping: 'Shopping',
    utilities: 'Utilities',
    insurance: 'Insurance',
    investmentFees: 'Investment Fees',
    taxes: 'Taxes',
    salary: 'Salary',
    investmentIncome: 'Investment Income',
    other: 'Other',
    
    // Category Manager
    manageCategories: 'Manage Categories',
    addManageCategoriesDesc: 'Add and manage categories for your transactions',
    categoryName: 'Category Name',
    categoryPlaceholder: 'e.g., Subscription, Gifts',
    addCategory: 'Add Category',
    categoryNameRequired: 'Category name is required',
    categoryExists: 'Category already exists',
    noCategoriesYet: 'No categories yet. Add your first category above.',
    both: 'Both',
    
    // Legal Pages
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    privacyPolicyIntroduction: 'Introduction',
    privacyPolicyIntroductionText: 'Welcome to Ascent ("we," "our," or "us"). We are committed to protecting your privacy and ensuring the security of your personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our financial management application.',
    informationWeCollect: 'Information We Collect',
    informationWeCollectText: 'We collect information that you provide directly to us, including:',
    personalInfoCollection: 'Personal information such as your name, email address, and profile information',
    financialDataCollection: 'Financial data including account information, transactions, budgets, and investment positions',
    preferencesCollection: 'User preferences and settings',
    usageDataCollection: 'Usage data and analytics to improve our services',
    howWeUseInformation: 'How We Use Your Information',
    howWeUseInformationText: 'We use the information we collect to:',
    provideServices: 'Provide, maintain, and improve our services',
    processTransactions: 'Process and manage your financial transactions and data',
    sendNotifications: 'Send you notifications, updates, and summaries (if enabled)',
    customerSupport: 'Respond to your inquiries and provide customer support',
    securityCompliance: 'Ensure security and prevent fraud',
    dataSecurity: 'Data Security',
    dataSecurityText: 'We implement appropriate technical and organizational security measures to protect your personal information. This includes encryption, secure data storage, and access controls. However, no method of transmission over the internet is 100% secure.',
    dataSharing: 'Data Sharing',
    dataSharingText: 'We do not sell your personal information. We may share your information only in the following circumstances:',
    withConsent: 'With your explicit consent',
    sharedUsers: 'With users you have explicitly granted access to (shared accounts)',
    legalRequirements: 'To comply with legal obligations',
    serviceProviders: 'With trusted service providers who assist in operating our services (under strict confidentiality agreements)',
    yourRights: 'Your Rights',
    yourRightsText: 'You have the right to:',
    accessData: 'Access and review your personal information',
    updateData: 'Update or correct your information',
    deleteData: 'Request deletion of your account and data',
    optOut: 'Opt out of certain communications',
    cookiesAndTracking: 'Cookies and Tracking',
    cookiesAndTrackingText: 'We use cookies and similar tracking technologies to enhance your experience, analyze usage patterns, and improve our services. You can control cookie preferences through your browser settings.',
    thirdPartyServices: 'Third-Party Services',
    thirdPartyServicesText: 'Our application may integrate with third-party services (such as Google OAuth for authentication). These services have their own privacy policies, and we encourage you to review them.',
    childrenPrivacy: "Children's Privacy",
    childrenPrivacyText: 'Our services are not intended for individuals under the age of 18. We do not knowingly collect personal information from children.',
    changesToPolicy: 'Changes to This Privacy Policy',
    changesToPolicyText: 'We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last Updated" date.',
    contactUsPrivacyText: 'If you have any questions about this Privacy Policy or our data practices, please contact us through the application settings or support channels.',
    termsIntroduction: 'Introduction',
    termsIntroductionText: 'Welcome to Ascent. These Terms of Service ("Terms") govern your access to and use of our financial management application and services ("Service"). By accessing or using our Service, you agree to be bound by these Terms.',
    acceptanceOfTerms: 'Acceptance of Terms',
    acceptanceOfTermsText: 'By creating an account, accessing, or using our Service, you acknowledge that you have read, understood, and agree to be bound by these Terms and our Privacy Policy. If you do not agree to these Terms, you may not use our Service.',
    eligibility: 'Eligibility',
    eligibilityText: 'You must be at least 18 years old to use our Service. By using our Service, you represent and warrant that you are of legal age to form a binding contract and meet all eligibility requirements.',
    accountRegistration: 'Account Registration',
    accountRegistrationText: 'To use our Service, you must:',
    provideAccurateInfo: 'Provide accurate, current, and complete information during registration',
    maintainAccountSecurity: 'Maintain and update your account information to keep it accurate',
    protectCredentials: 'Maintain the security of your account credentials',
    notifyUnauthorized: 'Notify us immediately of any unauthorized access or use of your account',
    useOfService: 'Use of Service',
    useOfServiceText: 'You agree to use our Service only for lawful purposes and in accordance with these Terms. You agree not to:',
    violateLaws: 'Violate any applicable laws or regulations',
    infringeRights: 'Infringe upon the rights of others',
    transmitHarmful: 'Transmit any harmful, malicious, or illegal content',
    interfereService: 'Interfere with or disrupt the Service or servers',
    attemptUnauthorized: 'Attempt to gain unauthorized access to any part of the Service',
    financialData: 'Financial Data and Information',
    financialDataText: 'You are solely responsible for the accuracy of all financial data and information you enter into the Service. We are not responsible for any errors, omissions, or inaccuracies in your data. The Service is provided for informational and organizational purposes only and should not be considered as financial, investment, or tax advice.',
    sharedAccounts: 'Shared Accounts',
    sharedAccountsText: 'If you share your account with other users, you are responsible for managing permissions and access levels. You acknowledge that shared users will have access to your financial data according to the permissions you grant. We are not responsible for any actions taken by shared users.',
    intellectualProperty: 'Intellectual Property',
    intellectualPropertyText: 'The Service and its original content, features, and functionality are owned by Ascent and are protected by international copyright, trademark, patent, trade secret, and other intellectual property laws. You may not reproduce, distribute, modify, or create derivative works of the Service without our express written permission.',
    disclaimers: 'Disclaimers',
    disclaimersText: 'THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE. WE ARE NOT RESPONSIBLE FOR ANY FINANCIAL DECISIONS MADE BASED ON INFORMATION PROVIDED BY THE SERVICE.',
    limitationOfLiability: 'Limitation of Liability',
    limitationOfLiabilityText: 'TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES.',
    termination: 'Termination',
    terminationText: 'We reserve the right to terminate or suspend your account and access to the Service immediately, without prior notice, for any reason, including if you breach these Terms. You may also terminate your account at any time through the application settings.',
    changesToTerms: 'Changes to Terms',
    changesToTermsText: 'We reserve the right to modify these Terms at any time. We will notify you of any material changes by posting the updated Terms on this page and updating the "Last Updated" date. Your continued use of the Service after such changes constitutes acceptance of the new Terms.',
    governingLaw: 'Governing Law',
    governingLawText: 'These Terms shall be governed by and construed in accordance with applicable laws, without regard to its conflict of law provisions.',
    contactUsTermsText: 'If you have any questions about these Terms of Service, please contact us through the application settings or support channels.',
    
    // Settings
    manageAccountPreferences: 'Manage your account and preferences',
    profileInformation: 'Profile Information',
    fullName: 'Full Name',
    email: 'Email',
    role: 'Role',
    fullNameUpdated: 'Full name updated successfully',
    failedToUpdateFullName: 'Failed to update full name',
    preferences: 'Preferences',
    language: 'Language',
    displayLanguage: 'Display language',
    defaultCurrency: 'Default Currency',
    primaryCurrencyForPortfolio: 'Primary currency for portfolio',
    theme: 'Theme',
    appColorScheme: 'App color scheme',
    dark: 'Dark',
    light: 'Light',
    privacy: 'Privacy',
    blurFinancialValues: 'Blur Financial Values',
    hideAmountsWhenShowing: 'Hide amounts when showing to others (privacy mode)',
    notifications: 'Notifications',
    priceAlerts: 'Price Alerts',
    getNotifiedPriceChanges: 'Get notified about significant price changes',
    dailySummary: 'Daily Summary',
    receiveDailyReports: 'Receive daily portfolio performance reports',
    weeklySummary: 'Weekly Summary',
    receiveWeeklyReports: 'Receive weekly portfolio performance reports',
    emailNotifications: 'Email Notifications',
    exportedSuccessfully: 'exported successfully',
    exportFailed: 'Failed to export data',
    receiveImportantUpdates: 'Receive important updates via email',
    sharedAccess: 'Shared Access',
    inviteUser: 'Invite User',
    noSharedUsersYet: 'No shared users yet',
    inviteFirstUser: 'Invite First User',
    importExport: 'Import / Export',
    paymentCards: 'Payment Cards',
    addCard: 'Add Card',
    noCardsYet: 'No cards added yet',
    cardName: 'Card Name',
    lastFourDigits: 'Last 4 Digits',
    cardType: 'Card Type',
    credit: 'Credit',
    debit: 'Debit',

    // Account Detail
    backToPortfolio: 'Back to Portfolio',
    refreshPrices: 'Refresh Prices',
    addPosition: 'Add Position',
    allocation: 'Allocation',
    topHoldings: 'Top Holdings',
    positionValue: 'Position Value',
    selectPosition: 'Select position',
    selectPositionToView: 'Select a position to view its value chart',
    positions: 'Positions',
    noPositionsYetAddFirst: 'No positions yet. Add your first position to get started.',
    accountNotFound: 'Account not found',
    currentPrice: 'Current Price',

    // Add Account Dialog
    addNewAccount: 'Add New Account',
    createNewInvestmentAccount: 'Create a new investment account to track your portfolio',
    accountName: 'Account Name',
    accountNamePlaceholder: 'e.g., Interactive Brokers',
    accountType: 'Account Type',
    initialInvestment: 'Initial Investment',
    notesOptional: 'Notes (Optional)',
    notesPlaceholder: 'Add any notes about this account...',
    deductFromCash: 'Deduct from cash balance',
    availableCash: 'Available cash',
    purchaseCost: 'Purchase cost',
    remainingCash: 'Remaining',
    insufficientCash: 'Insufficient cash for this purchase',
    cashReturned: 'Cash returned to account',
    cashAdded: 'Cash added to existing balance!',
    addToCash: 'Amount to Add',
    cashWillBeAdded: 'This will be added to your existing cash balance',
    createAccount: 'Create Account',
    creating: 'Creating...',

    // Add Position Dialog
    addNewPosition: 'Add New Position',
    editPosition: 'Edit Position',
    updatePositionDetails: 'Update position details',
    addNewStockEtf: 'Add a new stock, ETF, or other asset to your account',
    symbol: 'Symbol',
    symbolPlaceholder: 'e.g., AAPL',
    quantity: 'Quantity',
    avgPrice: 'Avg Price',
    addPositionBtn: 'Add Position',
    updatePositionBtn: 'Update Position',
    sellPosition: 'Sell Position',
    sellPositionDescription: 'Sell from your portfolio',
    position: 'Position',
    currentValue: 'Current Value',
    justDelete: 'Just Delete',
    sellAndReturnCash: 'Sell & Return to Cash',
    currentHolding: 'Current Holding',
    quantityToSell: 'Quantity to Sell',
    sellAll: 'Sell All',
    sellPrice: 'Sell Price per Unit',
    saleSummary: 'Sale Summary',
    totalProceeds: 'Total Proceeds',
    costBasis: 'Cost Basis',
    profitLoss: 'Profit/Loss',
    remaining: 'Remaining',
    addProceedsToCash: 'Add proceeds to cash balance',
    sellNotesPlaceholder: 'Reason for selling, market conditions, etc.',
    selling: 'Selling...',
    sellPartial: 'Sell',
    invalidQuantity: 'Invalid quantity',
    depositRecorded: 'Cash deposit recorded!',
    buyRecorded: 'Position purchased!',
    sellRecorded: 'Position sold!',
    positionDeleted: 'Position deleted!',
    depositAmount: 'Deposit Amount',
    currentCashBalance: 'Current cash balance',
    depositTrackedSeparately: 'Each deposit is tracked as a separate transaction',
    transactionHistory: 'Transaction History',
    buy: 'Buy',
    sell: 'Sell',
    deposit: 'Deposit',
    withdrawal: 'Withdrawal',
    noPortfolioTransactionsYet: 'No transactions yet',
    transactionsWillAppear: 'Buy, sell, and deposit transactions will appear here',
    price: 'Price',
    total: 'Total',

    // Dashboard Customization
    customizeDashboard: 'Customize Dashboard',
    resetToDefault: 'Reset to Default',
    saveLayout: 'Save Layout',

    // Widgets
    portfolioValueTrendTitle: 'Portfolio Value Trend',
    historicalPortfolioPerformance: 'Historical portfolio performance',
    netWorthChart: 'Net Worth Chart',
    assetsMinus: 'Assets minus cumulative expenses',
    accountAllocationTitle: 'Account Allocation',
    breakdownByAccountType: 'Breakdown by account type',
    assetAllocationTitle: 'Asset Allocation',
    distributionByAssetType: 'Distribution by asset type',
    accountSummaryTitle: 'Account Summary',
    listOfAllAccounts: 'List of all accounts',
    savingsRateTitle: 'Savings Rate',
    monthlySavingsPercentage: 'Monthly savings percentage',
    benchmarkComparisonTitle: 'Benchmark Comparison',
    performanceVsSP500Title: 'Performance vs S&P 500',
    financialGoalsTitle: 'Financial Goals',
    trackYourFinancialObjectives: 'Track your financial objectives',

    // Goal Dialog
    addFinancialGoal: 'Add Financial Goal',
    editFinancialGoal: 'Edit Financial Goal',
    setAndTrackObjectives: 'Set and track your financial objectives',
    goalTitle: 'Goal Title',
    goalTitlePlaceholder: 'e.g., Retirement Fund, Emergency Savings',
    targetAmount: 'Target Amount',
    targetDate: 'Target Date',
    expectedAnnualReturn: 'Expected Annual Return (%)',
    expectedReturnHelp: 'Used to calculate projected achievement date',
    linkInvestmentAccounts: 'Link Investment Accounts (Optional)',
    progressWillTrack: 'Progress will track automatically based on linked accounts',
    addGoalBtn: 'Add Goal',
    updateGoal: 'Update Goal',

    // Import/Export
    importExportData: 'Import & Export Data',
    importData: 'Import Data',
    exportData: 'Export Data',
    importType: 'Import Type',
    selectCsvFile: 'Select CSV File',
    accounts: 'Accounts',
    exportAll: 'Export All',
    downloadDataCsv: 'Download your data as CSV files for backup or analysis in other tools.',
    uploadCsvFormats: 'Upload CSV files with the following formats:',

    // Shared Users
    viewPortfolio: 'View Portfolio',
    editPortfolio: 'Edit Portfolio',
    viewExpenses: 'View Expenses',
    editExpenses: 'Edit Expenses',
    viewNotes: 'View Notes',
    editNotes: 'Edit Notes',
    viewGoals: 'View Goals',
    editGoals: 'Edit Goals',
    viewBudgets: 'View Budgets',
    editBudgets: 'Edit Budgets',
    viewSettings: 'View Settings',
    manageUsers: 'Manage Users',
    canSeeAccountsPositions: 'Can see accounts and positions',
    canAddEditAccountsPositions: 'Can add/edit accounts and positions',
    canSeeExpenseTransactions: 'Can see expense transactions',
    canAddEditExpenseTransactions: 'Can add/edit expense transactions',
    canSeeNotes: 'Can see notes and personal memos',
    canAddEditNotes: 'Can create, edit, and delete notes',
    canSeeFinancialGoals: 'Can see financial goals and progress',
    canAddEditFinancialGoals: 'Can create, edit, and delete financial goals',
    canSeeBudgets: 'Can see budget categories and limits',
    canAddEditBudgets: 'Can create, edit, and delete budgets',
    canAccessSettingsPage: 'Can access settings page',
    canInviteManageUsers: 'Can invite and manage users',
    emailAddress: 'Email Address',
    displayName: 'Display Name',
    permissions: 'Permissions',
    sendInvitation: 'Send Invitation',
    sending: 'Sending...',
    pending: 'pending',
    accepted: 'accepted',
    revoked: 'revoked',
    
    // Budget
    budgetTracking: 'Budget Tracking',
    manageBudgets: 'Manage Budgets',
    setBudgetLimits: 'Set monthly spending limits for different categories',
    allCategoriesHaveBudgets: 'All categories have budgets',
    deleteBudgetToAddNew: 'Delete an existing budget to add a new one, or edit existing budgets below.',
    monthlyLimit: 'Monthly Limit',
    alertThreshold: 'Alert Threshold',
    alertThresholdHelp: "You'll be alerted when spending reaches this percentage",
    updateBudget: 'Update Budget',
    addBudget: 'Add Budget',
    currentBudgets: 'Current Budgets',
    overBudgetBy: 'Over budget by',
    reachedLimit: 'Reached limit',
    approachingLimit: 'Approaching limit',
    perMonth: '/month',
    alertAt: 'Alert at',
    selectCategory: 'Select a category',
    
    // Period Selector
    year: 'Year',
    currentMonth: 'Current Month',
    clickToChangePeriod: 'Click to change period',
    futureMonth: 'Future month',
    noTransactions: 'No transactions',
    yearlyView: 'Yearly view',
    months: 'months',
    all: 'All',
    
    // Expense View
    cardPayments: 'Card Payments',
    cashPayments: 'Cash Payments',
    showing: 'Showing',
    of: 'of',
    
    // Months
    january: 'January',
    february: 'February',
    march: 'March',
    april: 'April',
    may: 'May',
    june: 'June',
    july: 'July',
    august: 'August',
    september: 'September',
    october: 'October',
    november: 'November',
    december: 'December',
    jan: 'Jan',
    feb: 'Feb',
    mar: 'Mar',
    apr: 'Apr',
    jun: 'Jun',
    jul: 'Jul',
    aug: 'Aug',
    sep: 'Sep',
    oct: 'Oct',
    nov: 'Nov',
    dec: 'Dec',
  },
  he: {
    // Navigation
    portfolio: 'תיק השקעות',
    dashboard: 'לוח בקרה',
    expenses: 'הוצאות',
    settings: 'הגדרות',
    menu: 'תפריט',
    notes: 'פתקים',
    notesDescription: 'הפתקים והרעיונות האישיים שלך',
    calendar: 'לוח שנה',
    googleCalendar: 'יומן גוגל',
    connectCalendar: 'חבר את היומן שלך',
    connectCalendarDesc: 'חבר את יומן גוגל שלך כדי לצפות ולנהל אירועים ישירות מהאפליקציה.',
    connectWithGoogle: 'התחבר עם גוגל',
    calendarConnected: 'יומן גוגל מחובר!',
    calendarDisconnected: 'היומן נותק',
    calendarSessionExpired: 'הסשן של היומן פג. אנא התחבר מחדש.',
    reconnect: 'התחבר מחדש',
    disconnect: 'נתק יומן',
    newEvent: 'אירוע חדש',
    newTask: 'משימה חדשה',
    taskTitle: 'כותרת המשימה',
    taskTitlePlaceholder: 'הוסף כותרת משימה',
    taskTitleRequired: 'כותרת המשימה נדרשת',
    taskCreated: 'המשימה נוצרה!',
    dueDate: 'תאריך יעד',
    addNotes: 'הוסף הערות',
    editEvent: 'עריכת אירוע',
    eventTitle: 'כותרת',
    eventTitlePlaceholder: 'הוסף כותרת',
    eventTitleRequired: 'כותרת האירוע נדרשת',
    eventCreated: 'האירוע נוצר!',
    eventUpdated: 'האירוע עודכן!',
    eventDeleted: 'האירוע נמחק!',
    startTime: 'התחלה',
    endTime: 'סיום',
    allDayEvent: 'אירוע יום שלם',
    allDay: 'יום שלם',
    location: 'מיקום',
    addLocation: 'הוסף מיקום',
    addDescription: 'הוסף תיאור',
    noEventsToday: 'אין אירועים מתוכננים',
    today: 'היום',
    day: 'יום',
    week: 'שבוע',
    month: 'חודש',
    calendarDescription: 'צפייה וניהול אירועי יומן גוגל',
    newNote: 'פתק חדש',
    editNote: 'עריכת פתק',
    noteTitle: 'כותרת',
    noteContent: 'כתוב את הפתק שלך...',
    noteColor: 'צבע',
    noteCreated: 'הפתק נוצר',
    noteUpdated: 'הפתק עודכן',
    noteDeleted: 'הפתק נמחק',
    noteTitleOrContentRequired: 'נא להוסיף כותרת או תוכן',
    searchNotes: 'חיפוש פתקים...',
    noNotesYet: 'אין עדיין פתקים',
    createFirstNote: 'צור את הפתק הראשון שלך כדי להתחיל',
    pinned: 'מוצמד',
    others: 'אחרים',
    pin: 'הצמד',
    unpin: 'בטל הצמדה',
    noContent: 'אין תוכן',
    tags: 'תגיות',
    addTag: 'הוסף תגית...',
    logout: 'התנתק',
    sessionExpired: 'פג תוקף החיבור. אנא התחבר שוב.',
    sessionExpiringSoon: 'החיבור שלך יפוג בעוד דקה בשל חוסר פעילות.',
    ascend: 'Ascent',
    ascendTagline: 'התעלה מעל יעדיך הפיננסיים',
    
    // User Menu
    owner: 'בעלים',
    sharedUser: 'משתמש משותף',
    darkMode: 'מצב כהה',
    blurValues: 'טשטש ערכים',
    user: 'משתמש',
    
    // Common
    loading: 'טוען...',
    save: 'שמור',
    create: 'צור',
    cancel: 'בטל',
    created: 'נוצר',
    updated: 'עודכן',
    delete: 'מחק',
    edit: 'ערוך',
    duplicate: 'שכפל',
    add: 'הוסף',
    close: 'סגור',
    confirm: 'אשר',
    search: 'חיפוש',
    filter: 'סינון',
    clearFilters: 'נקה סינונים',
    results: 'תוצאות',
    result: 'תוצאה',
    saving: 'שומר...',
    updating: 'מעדכן...',
    adding: 'מוסיף...',
    deleting: 'מוחק...',
    optional: 'אופציונלי',
    confirmDelete: 'אשר מחיקה',
    confirmDeletePosition: 'האם אתה בטוח שברצונך למחוק את הפוזיציה הזו? פעולה זו לא ניתנת לביטול.',
    confirmDeleteDayTrade: 'האם אתה בטוח שברצונך למחוק את המסחר היומי הזה? פעולה זו לא ניתנת לביטול.',
    confirmDeleteAllPositions: 'האם אתה בטוח שברצונך למחוק את כל הפוזיציות עבור {symbol}? פעולה זו לא ניתנת לביטול.',
    
    // Login/Register
    welcome: 'ברוכים הבאים',
    signInToAccount: 'התחבר לחשבון שלך או צור חשבון חדש',
    orContinueWithEmail: 'או המשך עם אימייל',
    login: 'התחברות',
    register: 'הרשמה',
    signIn: 'התחבר',
    signingIn: 'מתחבר...',
    creatingAccount: 'יוצר חשבון...',
    password: 'סיסמה',
    confirmPassword: 'אשר סיסמה',
    welcomeBack: 'ברוך שובך!',
    accountCreated: 'החשבון נוצר בהצלחה!',
    passwordsDoNotMatch: 'הסיסמאות לא תואמות',
    passwordMinLength: 'הסיסמה חייבת להכיל לפחות 6 תווים',
    loginFailed: 'ההתחברות נכשלה',
    registrationFailed: 'ההרשמה נכשלה',
    googleSignInFailed: 'ההתחברות עם גוגל נכשלה',
    continueWithGoogle: 'המשך עם גוגל',
    
    // Payment Methods
    paymentMethod: 'אמצעי תשלום',
    selectPaymentMethod: 'בחר אמצעי תשלום',
    selectCard: 'בחר כרטיס',
    selectACard: 'בחר כרטיס',
    noCardsAvailable: 'אין כרטיסים זמינים - הוסף בהגדרות',
    card: 'כרטיס',
    cash: 'מזומן',
    transfer: 'העברה',
    
    // Dashboard
    yourCompleteFinancialOverview: 'סקירה פינסית מלאה',
    customize: 'התאמה אישית',
    totalPortfolio: 'סך תיק',
    totalPnL: 'רווח/הפסד',
    invested: 'מושקע',
    savingsRate: 'שיעור חיסכון',
    ofPortfolio: 'מהתיק',
    thisMonth: 'החודש',
    portfolioValue: 'ערך התיק',
    portfolioValueTrend: 'מגמת ערך התיק',
    last30Days: '30 יום אחרונים',
    netWorth: 'שווי נטו',
    netWorthTrend: 'מגמת שווי נטו (30 יום)',
    allocationByAccountType: 'חלוקה לפי סוג חשבון',
    assetAllocation: 'חלוקת נכסים',
    performanceVsSP500: 'ביצועים מול S&P 500',
    yourPortfolio: 'התיק שלך',
    sp500Benchmark: 'מדד S&P 500',
    difference: 'הפרש',
    outperforming: 'עולה על הציפיות',
    underperforming: 'מתחת לציפיות',
    financialGoals: 'יעדים פיננסיים',
    addGoal: 'הוסף יעד',
    noGoalsYet: 'אין יעדים פיננסיים עדיין',
    setYourFirstGoal: 'הגדר יעד ראשון',
    accountSummary: 'סיכום חשבונות',
    noAccountsYet: 'אין חשבונות עדיין. צור את החשבון הראשון שלך',
    
    // Portfolio
    investmentAccounts: 'חשבונות השקעה',
    addAccount: 'הוסף חשבון',
    noAccountsCreateFirst: 'אין חשבונות עדיין. צור את חשבון ההשקעה הראשון שלך להתחיל למעקב אחר התיק',
    totalValue: 'ערך כולל',
    totalPortfolioValue: 'ערך תיק כולל',
    totalReturn: 'תשואה כוללת',
    trackAndManageAccounts: 'מעקב וניהול חשבונות ההשקעה שלך',
    createYourFirstAccount: 'צור את החשבון הראשון שלך',
    noAccountsYetTitle: 'אין חשבונות עדיין',
    accountTypeInvestment: 'השקעה',
    accountTypeRetirement: 'פנסיה',
    accountTypeIRA: 'קרן פנסיה',
    accountTypePension: 'פנסיה',
    accountTypeSavings: 'חיסכון',
    accountTypeOther: 'אחר',
    accountCreatedSuccessfully: 'החשבון נוצר בהצלחה!',
    failedToCreateAccount: 'יצירת החשבון נכשלה',
    accountDeletedSuccessfully: 'החשבון נמחק בהצלחה!',
    failedToDeleteAccount: 'מחיקת החשבון נכשלה',
    done: 'סיום',
    
    // Success/Error Messages
    goalCreatedSuccessfully: 'היעד נוצר בהצלחה!',
    goalUpdatedSuccessfully: 'היעד עודכן בהצלחה!',
    goalDeletedSuccessfully: 'היעד נמחק בהצלחה!',
    dashboardLayoutSaved: 'פריסת לוח הבקרה נשמרה!',
    transactionAddedSuccessfully: 'התנועה נוספה בהצלחה!',
    transactionUpdatedSuccessfully: 'התנועה עודכנה בהצלחה!',
    transactionDeletedSuccessfully: 'התנועה נמחקה בהצלחה!',
    failedToAddTransaction: 'הוספת התנועה נכשלה',
    failedToUpdateTransaction: 'עדכון התנועה נכשל',
    failedToDeleteTransaction: 'מחיקת התנועה נכשלה',
    deleteTransaction: 'מחיקת תנועה',
    deleteTransactionConfirmation: 'האם אתה בטוח שברצונך למחוק את התנועה הזו? פעולה זו לא ניתנת לביטול.',
    budgetCreatedSuccessfully: 'התקציב נוצר בהצלחה!',
    budgetUpdatedSuccessfully: 'התקציב עודכן בהצלחה!',
    budgetDeletedSuccessfully: 'התקציב נמחק בהצלחה!',
    failedToCreateBudget: 'יצירת התקציב נכשלה',
    failedToUpdateBudget: 'עדכון התקציב נכשל',
    failedToDeleteBudget: 'מחיקת התקציב נכשלה',
    categoryCreatedSuccessfully: 'הקטגוריה נוצרה בהצלחה!',
    categoryDeletedSuccessfully: 'הקטגוריה נמחקה בהצלחה!',
    failedToCreateCategory: 'יצירת הקטגוריה נכשלה',
    failedToDeleteCategory: 'מחיקת הקטגוריה נכשלה',
    pleaseFillAllFields: 'אנא מלא את כל השדות',
    last4DigitsMustBe4: '4 ספרות אחרונות חייבות להיות בדיוק 4 מספרים',
    
    // Expenses
    incomeExpenseTracking: 'מעקב הכנסות והוצאות',
    manageYourFinances: 'נהל את הכספים שלך ועקוב אחר ההוצאות',
    addTransaction: 'הוסף תנועה',
    totalIncome: 'הכנסות כוללות',
    totalExpenses: 'הוצאות כוללות',
    netAmount: 'סכום נטו',
    net: 'נטו',
    expensesByCategory: 'הוצאות לפי קטגוריה',
    expensesByPaymentMethod: 'הוצאות לפי אמצעי תשלום',
    noPaymentMethodData: 'אין נתוני אמצעי תשלום',
    noDataAvailable: 'אין נתונים זמינים',
    noPositionsYet: 'אין עדיין פוזיציות',
    monthlyTrend: 'מגמה חודשית',
    monthlyTrendLast6: 'מגמה חודשית (6 חודשים אחרונים)',
    noTransactionsYet: 'אין תנועות עדיין',
    startTrackingFinances: 'התחל לעקוב אחר הכספים שלך על ידי הוספת תנועה ראשונה',
    trackYourIncomeExpenses: 'מעקב אחר ההכנסות וההוצאות שלך',
    incomeThisMonth: 'הכנסות (החודש)',
    expensesThisMonth: 'הוצאות (החודש)',
    transactions: 'תנועות',
    searchTransactions: 'חיפוש תנועות...',
    noExpenseData: 'אין נתוני הוצאות זמינים',
    income: 'הכנסה',
    expense: 'הוצאה',

    // Transaction Dialog
    editTransaction: 'עריכת תנועה',
    duplicateTransaction: 'שכפול תנועה',
    duplicateTransactionDescription: 'צור עותק של תנועה זו עם תאריך היום',
    addTransactionTitle: 'הוסף תנועה',
    updateTransactionDetails: 'עדכן פרטי תנועה',
    recordNewTransaction: 'רשום תנועת הכנסה או הוצאה חדשה',
    date: 'תאריך',
    type: 'סוג',
    category: 'קטגוריה',
    description: 'תיאור',
    amount: 'סכום',
    currency: 'מטבע',
    relatedAccount: 'חשבון קשור (אופציונלי)',
    selectAccountOptional: 'בחר חשבון (אופציונלי)',
    none: 'ללא',
    linkTransactionToAccount: 'קשר תנועה זו לחשבון השקעה במידת הצורך',
    updateTransaction: 'עדכן תנועה',
    dateRequired: 'תאריך נדרש',
    descriptionRequired: 'תיאור נדרש',
    amountGreaterThanZero: 'הסכום חייב להיות גדול מ-0',
    descriptionPlaceholder: 'לדוגמה: קניות במרכול',

    // Transaction Filters
    filters: 'סינונים',
    clear: 'נקה',
    last7Days: '7 ימים אחרונים',
    allTime: 'כל הזמן',
    fromDate: 'מתאריך',
    toDate: 'עד תאריך',
    allTypes: 'כל הסוגים',
    expensesOnly: 'הוצאות בלבד',
    incomeOnly: 'הכנסות בלבד',
    allCategories: 'כל הקטגוריות',

    // Transaction List
    noTransactionsFound: 'לא נמצאו תנועות',
    addFirstTransactionOrAdjust: 'הוסף את התנועה הראשונה או שנה את הסינונים',

    // Categories
    foodDining: 'אוכל ומסעדות',
    groceries: 'מכולת',
    rentHousing: 'שכירות ודיור',
    transportation: 'תחבורה',
    healthcare: 'בריאות',
    entertainment: 'בידור',
    shopping: 'קניות',
    utilities: 'חשבונות',
    insurance: 'ביטוח',
    investmentFees: 'עמלות השקעה',
    taxes: 'מיסים',
    salary: 'משכורת',
    investmentIncome: 'הכנסות מהשקעות',
    other: 'אחר',
    
    // Category Manager
    manageCategories: 'ניהול קטגוריות',
    addManageCategoriesDesc: 'הוסף ונהל קטגוריות לתנועות שלך',
    categoryName: 'שם קטגוריה',
    categoryPlaceholder: 'למשל, מנוי, מתנות',
    addCategory: 'הוסף קטגוריה',
    categoryNameRequired: 'שם קטגוריה נדרש',
    categoryExists: 'קטגוריה כבר קיימת',
    noCategoriesYet: 'אין קטגוריות עדיין. הוסף את הקטגוריה הראשונה למעלה.',
    both: 'שניהם',
    
    // Settings
    manageAccountPreferences: 'נהל את החשבון וההעדפות שלך',
    profileInformation: 'מידע אישי',
    fullName: 'שם מלא',
    email: 'אימייל',
    role: 'תפקיד',
    fullNameUpdated: 'שם מלא עודכן בהצלחה',
    failedToUpdateFullName: 'נכשל בעדכון שם מלא',
    preferences: 'העדפות',
    language: 'שפה',
    displayLanguage: 'שפת התצוגה',
    defaultCurrency: 'מטבע ברירת מחדל',
    primaryCurrencyForPortfolio: 'מטבע עיקרי לתיק',
    theme: 'ערכת נושא',
    appColorScheme: 'סכמת צבעים',
    dark: 'כהה',
    light: 'בהיר',
    privacy: 'פרטיות',
    blurFinancialValues: 'טשטש ערכים פיננסיים',
    hideAmountsWhenShowing: 'הסתר סכומים בעת הצגה לאחרים (מצב פרטיות)',
    notifications: 'התראות',
    priceAlerts: 'התראות מחיר',
    getNotifiedPriceChanges: 'קבל התראות על שינויי מחיר משמעותיים',
    dailySummary: 'סיכום יומי',
    receiveDailyReports: 'קבל דוחות ביצועים יומיים',
    weeklySummary: 'סיכום שבועי',
    receiveWeeklyReports: 'קבל דוחות ביצועים שבועיים',
    emailNotifications: 'התראות אימייל',
    exportedSuccessfully: 'יוצא בהצלחה',
    exportFailed: 'ייצוא נכשל',
    receiveImportantUpdates: 'קבל עדכונים חשובים באימייל',
    sharedAccess: 'גישה משותפת',
    inviteUser: 'הזמן משתמש',
    noSharedUsersYet: 'אין משתמשים משותפים עדיין',
    inviteFirstUser: 'הזמן משתמש ראשון',
    importExport: 'ייבוא / ייצוא',
    paymentCards: 'כרטיסי תשלום',
    addCard: 'הוסף כרטיס',
    noCardsYet: 'לא נוספו כרטיסים עדיין',
    cardName: 'שם הכרטיס',
    lastFourDigits: '4 ספרות אחרונות',
    cardType: 'סוג כרטיס',
    credit: 'אשראי',
    debit: 'חיוב',

    // Account Detail
    backToPortfolio: 'חזרה לתיק',
    refreshPrices: 'רענן מחירים',
    addPosition: 'הוסף פוזיציה',
    allocation: 'חלוקה',
    topHoldings: 'אחזקות מובילות',
    positionValue: 'ערך פוזיציה',
    selectPosition: 'בחר פוזיציה',
    selectPositionToView: 'בחר פוזיציה כדי לצפות בגרף הערך שלה',
    positions: 'פוזיציות',
    noPositionsYetAddFirst: 'אין פוזיציות עדיין. הוסף את הפוזיציה הראשונה',
    accountNotFound: 'החשבון לא נמצא',
    currentPrice: 'מחיר נוכחי',

    // Add Account Dialog
    addNewAccount: 'הוסף חשבון חדש',
    createNewInvestmentAccount: 'צור חשבון השקעה חדש למעקב אחר התיק',
    accountName: 'שם החשבון',
    accountNamePlaceholder: 'לדוגמה: אינטראקטיב ברוקרס',
    accountType: 'סוג חשבון',
    initialInvestment: 'השקעה ראשונית',
    notesOptional: 'הערות (אופציונלי)',
    notesPlaceholder: 'הוסף הערות על חשבון זה...',
    deductFromCash: 'נכה מיתרת המזומנים',
    availableCash: 'מזומן זמין',
    purchaseCost: 'עלות רכישה',
    remainingCash: 'יתרה',
    insufficientCash: 'אין מספיק מזומנים לרכישה זו',
    cashReturned: 'המזומן הוחזר לחשבון',
    cashAdded: 'מזומן נוסף ליתרה הקיימת!',
    addToCash: 'סכום להוספה',
    cashWillBeAdded: 'זה יתווסף ליתרת המזומנים הקיימת שלך',
    createAccount: 'צור חשבון',
    creating: 'יוצר...',

    // Add Position Dialog
    addNewPosition: 'הוסף פוזיציה חדשה',
    editPosition: 'ערוך פוזיציה',
    updatePositionDetails: 'עדכן פרטי פוזיציה',
    addNewStockEtf: 'הוסף מניה, ETF או נכס אחר לחשבון שלך',
    symbol: 'סימול',
    symbolPlaceholder: 'לדוגמה: AAPL',
    quantity: 'כמות',
    avgPrice: 'מחיר ממוצע',
    addPositionBtn: 'הוסף פוזיציה',
    updatePositionBtn: 'עדכן פוזיציה',
    sellPosition: 'מכירת פוזיציה',
    sellPositionDescription: 'מכירה מהתיק שלך',
    position: 'פוזיציה',
    currentValue: 'ערך נוכחי',
    justDelete: 'רק מחק',
    sellAndReturnCash: 'מכור והחזר למזומן',
    currentHolding: 'החזקה נוכחית',
    quantityToSell: 'כמות למכירה',
    sellAll: 'מכור הכל',
    sellPrice: 'מחיר מכירה ליחידה',
    saleSummary: 'סיכום מכירה',
    totalProceeds: 'סך התמורה',
    costBasis: 'בסיס עלות',
    profitLoss: 'רווח/הפסד',
    remaining: 'נותר',
    addProceedsToCash: 'הוסף תמורה ליתרת מזומנים',
    sellNotesPlaceholder: 'סיבת המכירה, תנאי שוק וכו\'',
    selling: 'מוכר...',
    sellPartial: 'מכור',
    invalidQuantity: 'כמות לא תקינה',
    depositRecorded: 'הפקדת מזומן נרשמה!',
    buyRecorded: 'פוזיציה נרכשה!',
    sellRecorded: 'פוזיציה נמכרה!',
    positionDeleted: 'פוזיציה נמחקה!',
    depositAmount: 'סכום הפקדה',
    currentCashBalance: 'יתרת מזומנים נוכחית',
    depositTrackedSeparately: 'כל הפקדה נרשמת כעסקה נפרדת',
    transactionHistory: 'היסטוריית עסקאות',
    buy: 'קנייה',
    sell: 'מכירה',
    deposit: 'הפקדה',
    withdrawal: 'משיכה',
    noPortfolioTransactionsYet: 'אין עסקאות עדיין',
    transactionsWillAppear: 'עסקאות קנייה, מכירה והפקדה יופיעו כאן',
    price: 'מחיר',
    total: 'סה"כ',

    // Dashboard Customization
    customizeDashboard: 'התאמה אישית של לוח הבקרה',
    resetToDefault: 'איפוס לברירת מחדל',
    saveLayout: 'שמור פריסה',

    // Widgets
    portfolioValueTrendTitle: 'מגמת ערך התיק',
    historicalPortfolioPerformance: 'ביצועי תיק היסטוריים',
    netWorthChart: 'תרשים שווי נטו',
    assetsMinus: 'נכסים פחות הוצאות מצטברות',
    accountAllocationTitle: 'חלוקת חשבונות',
    breakdownByAccountType: 'פירוט לפי סוג חשבון',
    assetAllocationTitle: 'חלוקת נכסים',
    distributionByAssetType: 'התפלגות לפי סוג נכס',
    accountSummaryTitle: 'סיכום חשבונות',
    listOfAllAccounts: 'רשימת כל החשבונות',
    savingsRateTitle: 'שיעור חיסכון',
    monthlySavingsPercentage: 'אחוז חיסכון חודשי',
    benchmarkComparisonTitle: 'השוואה למדד',
    performanceVsSP500Title: 'ביצועים מול S&P 500',
    financialGoalsTitle: 'יעדים פיננסיים',
    trackYourFinancialObjectives: 'עקוב אחר היעדים הפיננסיים שלך',

    // Goal Dialog
    addFinancialGoal: 'הוסף יעד פיננסי',
    editFinancialGoal: 'ערוך יעד פיננסי',
    setAndTrackObjectives: 'הגדר ועקוב אחר יעדים פיננסיים',
    goalTitle: 'כותרת היעד',
    goalTitlePlaceholder: 'לדוגמה: קרן פנסיה, קרן חירום',
    targetAmount: 'סכום יעד',
    currentAmountGoal: 'סכום נוכחי',
    targetDate: 'תאריך יעד',
    expectedAnnualReturn: 'תשואה שנתית צפויה (%)',
    expectedReturnHelp: 'משמש לחישוב תאריך השגת היעד הצפוי',
    linkInvestmentAccounts: 'קשר לחשבונות השקעה (אופציונלי)',
    progressWillTrack: 'התקדמות תעקוב אוטומטית על סמך חשבונות מקושרים',
    addGoalBtn: 'הוסף יעד',
    updateGoal: 'עדכן יעד',

    // Import/Export
    importExportData: 'ייבוא וייצוא נתונים',
    importData: 'ייבוא נתונים',
    exportData: 'ייצוא נתונים',
    importType: 'סוג ייבוא',
    selectCsvFile: 'בחר קובץ CSV',
    accounts: 'חשבונות',
    exportAll: 'ייצא הכל',
    downloadDataCsv: 'הורד את הנתונים שלך כקבצי CSV לגיבוי או ניתוח בכלים אחרים.',
    uploadCsvFormats: 'העלה קבצי CSV בפורמטים הבאים:',

    // Shared Users
    viewPortfolio: 'צפה בתיק',
    editPortfolio: 'ערוך תיק',
    viewExpenses: 'צפה בהוצאות',
    editExpenses: 'ערוך הוצאות',
    viewNotes: 'צפה בפתקים',
    editNotes: 'ערוך פתקים',
    viewGoals: 'צפה ביעדים',
    editGoals: 'ערוך יעדים',
    viewBudgets: 'צפה בתקציבים',
    editBudgets: 'ערוך תקציבים',
    viewSettings: 'צפה בהגדרות',
    manageUsers: 'נהל משתמשים',
    canSeeAccountsPositions: 'יכול לראות חשבונות ופוזיציות',
    canAddEditAccountsPositions: 'יכול להוסיף/לערוך חשבונות ופוזיציות',
    canSeeExpenseTransactions: 'יכול לראות תנועות הוצאות',
    canAddEditExpenseTransactions: 'יכול להוסיף/לערוך תנועות הוצאות',
    canSeeNotes: 'יכול לראות פתקים ומזכרות אישיות',
    canAddEditNotes: 'יכול ליצור, לערוך ולמחוק פתקים',
    canSeeFinancialGoals: 'יכול לראות יעדים פיננסיים והתקדמות',
    canAddEditFinancialGoals: 'יכול ליצור, לערוך ולמחוק יעדים פיננסיים',
    canSeeBudgets: 'יכול לראות קטגוריות תקציב ומגבלות',
    canAddEditBudgets: 'יכול ליצור, לערוך ולמחוק תקציבים',
    canAccessSettingsPage: 'יכול לגשת לעמוד ההגדרות',
    canInviteManageUsers: 'יכול להזמין ולנהל משתמשים',
    emailAddress: 'כתובת אימייל',
    displayName: 'שם תצוגה',
    permissions: 'הרשאות',
    sendInvitation: 'שלח הזמנה',
    sending: 'שולח...',
    pending: 'ממתין',
    accepted: 'אושר',
    revoked: 'בוטל',
    
    // Budget
    budgetTracking: 'מעקב תקציב',
    manageBudgets: 'ניהול תקציבים',
    setBudgetLimits: 'הגדר מגבלות הוצאה חודשיות לקטגוריות שונות',
    allCategoriesHaveBudgets: 'לכל הקטגוריות יש תקציבים',
    deleteBudgetToAddNew: 'מחק תקציב קיים כדי להוסיף חדש, או ערוך תקציבים קיימים למטה.',
    monthlyLimit: 'מגבלה חודשית',
    alertThreshold: 'סף התראה',
    alertThresholdHelp: 'תקבל התראה כשההוצאה תגיע לאחוז הזה',
    updateBudget: 'עדכן תקציב',
    addBudget: 'הוסף תקציב',
    currentBudgets: 'תקציבים נוכחיים',
    overBudgetBy: 'חריגה מהתקציב ב-',
    reachedLimit: 'הגעת למגבלה',
    approachingLimit: 'מתקרב למגבלה',
    perMonth: '/חודש',
    alertAt: 'התראה ב-',
    selectCategory: 'בחר קטגוריה',
    
    // Period Selector
    year: 'שנה',
    currentMonth: 'החודש הנוכחי',
    clickToChangePeriod: 'לחץ לשינוי התקופה',
    futureMonth: 'חודש עתידי',
    noTransactions: 'אין תנועות',
    yearlyView: 'תצוגה שנתית',
    months: 'חודשים',
    all: 'הכל',
    
    // Expense View
    cardPayments: 'תשלומי כרטיס',
    cashPayments: 'תשלומי מזומן',
    showing: 'מציג',
    of: 'מתוך',
    
    // Months
    january: 'ינואר',
    february: 'פברואר',
    march: 'מרץ',
    april: 'אפריל',
    may: 'מאי',
    june: 'יוני',
    july: 'יולי',
    august: 'אוגוסט',
    september: 'ספטמבר',
    october: 'אוקטובר',
    november: 'נובמבר',
    december: 'דצמבר',
    jan: 'ינו',
    feb: 'פבר',
    mar: 'מרץ',
    apr: 'אפר',
    jun: 'יוני',
    jul: 'יולי',
    aug: 'אוג',
    sep: 'ספט',
    oct: 'אוק',
    nov: 'נוב',
    dec: 'דצמ',
  },
  ru: {
    // Navigation
    portfolio: 'Портфель',
    dashboard: 'Панель',
    expenses: 'Расходы',
    settings: 'Настройки',
    menu: 'Меню',
    notes: 'Заметки',
    notesDescription: 'Ваши личные заметки и идеи',
    calendar: 'Календарь',
    googleCalendar: 'Google Календарь',
    connectCalendar: 'Подключите календарь',
    connectCalendarDesc: 'Подключите Google Календарь для просмотра и управления событиями прямо из приложения.',
    connectWithGoogle: 'Подключить через Google',
    calendarConnected: 'Google Календарь подключен!',
    calendarDisconnected: 'Календарь отключен',
    calendarSessionExpired: 'Сессия календаря истекла. Пожалуйста, переподключитесь.',
    reconnect: 'Переподключить',
    disconnect: 'Отключить календарь',
    newEvent: 'Новое событие',
    newTask: 'Новая задача',
    taskTitle: 'Название задачи',
    taskTitlePlaceholder: 'Добавить название задачи',
    taskTitleRequired: 'Название задачи обязательно',
    taskCreated: 'Задача создана!',
    dueDate: 'Срок выполнения',
    addNotes: 'Добавить заметки',
    editEvent: 'Редактировать событие',
    eventTitle: 'Название',
    eventTitlePlaceholder: 'Добавить название',
    eventTitleRequired: 'Название события обязательно',
    eventCreated: 'Событие создано!',
    eventUpdated: 'Событие обновлено!',
    eventDeleted: 'Событие удалено!',
    startTime: 'Начало',
    endTime: 'Конец',
    allDayEvent: 'Весь день',
    allDay: 'Весь день',
    location: 'Место',
    addLocation: 'Добавить место',
    addDescription: 'Добавить описание',
    noEventsToday: 'Нет запланированных событий',
    today: 'Сегодня',
    day: 'День',
    week: 'Неделя',
    month: 'Месяц',
    calendarDescription: 'Просмотр и управление событиями Google Календаря',
    newNote: 'Новая заметка',
    editNote: 'Редактировать заметку',
    noteTitle: 'Заголовок',
    noteContent: 'Напишите вашу заметку...',
    noteColor: 'Цвет',
    noteCreated: 'Заметка создана',
    noteUpdated: 'Заметка обновлена',
    noteDeleted: 'Заметка удалена',
    noteTitleOrContentRequired: 'Добавьте заголовок или содержание',
    searchNotes: 'Поиск заметок...',
    noNotesYet: 'Заметок пока нет',
    createFirstNote: 'Создайте первую заметку для начала',
    pinned: 'Закреплённые',
    others: 'Другие',
    pin: 'Закрепить',
    unpin: 'Открепить',
    noContent: 'Нет содержания',
    tags: 'Теги',
    addTag: 'Добавить тег...',
    logout: 'Выйти',
    sessionExpired: 'Сессия истекла. Пожалуйста, войдите снова.',
    sessionExpiringSoon: 'Ваша сессия истечёт через 1 минуту из-за неактивности.',
    ascend: 'Ascent',
    ascendTagline: 'Поднимитесь выше своих финансовых целей',
    
    // User Menu
    owner: 'Владелец',
    sharedUser: 'Общий пользователь',
    darkMode: 'Тёмный режим',
    blurValues: 'Размыть значения',
    user: 'Пользователь',
    
    // Common
    loading: 'Загрузка...',
    save: 'Сохранить',
    create: 'Создать',
    cancel: 'Отмена',
    created: 'Создано',
    updated: 'Обновлено',
    delete: 'Удалить',
    edit: 'Редактировать',
    duplicate: 'Дублировать',
    add: 'Добавить',
    close: 'Закрыть',
    confirm: 'Подтвердить',
    search: 'Поиск',
    filter: 'Фильтр',
    clearFilters: 'Очистить фильтры',
    results: 'результатов',
    result: 'результат',
    saving: 'Сохранение...',
    updating: 'Обновление...',
    adding: 'Добавление...',
    deleting: 'Удаление...',
    optional: 'Необязательно',
    confirmDelete: 'Подтвердить удаление',
    confirmDeletePosition: 'Вы уверены, что хотите удалить эту позицию? Это действие нельзя отменить.',
    confirmDeleteDayTrade: 'Вы уверены, что хотите удалить эту дневную сделку? Это действие нельзя отменить.',
    confirmDeleteAllPositions: 'Вы уверены, что хотите удалить все позиции для {symbol}? Это действие нельзя отменить.',
    
    // Login/Register
    welcome: 'Добро пожаловать',
    signInToAccount: 'Войдите в свой аккаунт или создайте новый',
    orContinueWithEmail: 'или продолжить с email',
    login: 'Вход',
    register: 'Регистрация',
    signIn: 'Войти',
    signingIn: 'Вход...',
    creatingAccount: 'Создание аккаунта...',
    password: 'Пароль',
    confirmPassword: 'Подтвердите пароль',
    welcomeBack: 'С возвращением!',
    accountCreated: 'Аккаунт успешно создан!',
    passwordsDoNotMatch: 'Пароли не совпадают',
    passwordMinLength: 'Пароль должен содержать минимум 6 символов',
    loginFailed: 'Ошибка входа',
    registrationFailed: 'Ошибка регистрации',
    googleSignInFailed: 'Ошибка входа через Google',
    continueWithGoogle: 'Продолжить с Google',
    
    // Payment Methods
    paymentMethod: 'Способ оплаты',
    selectPaymentMethod: 'Выберите способ оплаты',
    selectCard: 'Выберите карту',
    selectACard: 'Выберите карту',
    noCardsAvailable: 'Нет доступных карт - Добавьте в настройках',
    card: 'Карта',
    cash: 'Наличные',
    transfer: 'Перевод',
    
    // Dashboard
    yourCompleteFinancialOverview: 'Полный финансовый обзор',
    customize: 'Настроить',
    totalPortfolio: 'Весь портфель',
    totalPnL: 'Общий P&L',
    invested: 'Инвестировано',
    savingsRate: 'Норма сбережений',
    ofPortfolio: 'портфеля',
    thisMonth: 'В этом месяце',
    portfolioValue: 'Стоимость портфеля',
    portfolioValueTrend: 'Тренд стоимости портфеля',
    last30Days: 'Последние 30 дней',
    netWorth: 'Чистая стоимость',
    netWorthTrend: 'Тренд чистой стоимости (30 дней)',
    allocationByAccountType: 'Распределение по типу счета',
    assetAllocation: 'Распределение активов',
    performanceVsSP500: 'Производительность vs S&P 500',
    yourPortfolio: 'Ваш портфель',
    sp500Benchmark: 'Бенчмарк S&P 500',
    difference: 'Разница',
    outperforming: 'Превосходит',
    underperforming: 'Отстает',
    financialGoals: 'Финансовые цели',
    addGoal: 'Добавить цель',
    noGoalsYet: 'Финансовых целей пока нет',
    setYourFirstGoal: 'Установите первую цель',
    accountSummary: 'Сводка счетов',
    noAccountsYet: 'Счетов пока нет. Создайте свой первый счет',
    
    // Portfolio
    investmentAccounts: 'Инвестиционные счета',
    addAccount: 'Добавить счет',
    noAccountsCreateFirst: 'Счетов пока нет. Создайте свой первый инвестиционный счет для отслеживания портфеля',
    totalValue: 'Общая стоимость',
    totalPortfolioValue: 'Общая стоимость портфеля',
    totalReturn: 'Общая доходность',
    trackAndManageAccounts: 'Отслеживайте и управляйте своими инвестиционными счетами',
    createYourFirstAccount: 'Создать первый счет',
    noAccountsYetTitle: 'Счетов пока нет',
    accountTypeInvestment: 'Инвестиции',
    accountTypeRetirement: 'Пенсионный',
    accountTypeIRA: 'IRA',
    accountTypePension: 'Пенсия',
    accountTypeSavings: 'Сбережения',
    accountTypeOther: 'Другое',
    accountCreatedSuccessfully: 'Счет успешно создан!',
    failedToCreateAccount: 'Не удалось создать счет',
    accountDeletedSuccessfully: 'Счет успешно удален!',
    failedToDeleteAccount: 'Не удалось удалить счет',
    done: 'Готово',
    
    // Success/Error Messages
    goalCreatedSuccessfully: 'Цель успешно создана!',
    goalUpdatedSuccessfully: 'Цель успешно обновлена!',
    goalDeletedSuccessfully: 'Цель успешно удалена!',
    dashboardLayoutSaved: 'Макет панели сохранен!',
    transactionAddedSuccessfully: 'Транзакция успешно добавлена!',
    transactionUpdatedSuccessfully: 'Транзакция успешно обновлена!',
    transactionDeletedSuccessfully: 'Транзакция успешно удалена!',
    failedToAddTransaction: 'Не удалось добавить транзакцию',
    failedToUpdateTransaction: 'Не удалось обновить транзакцию',
    failedToDeleteTransaction: 'Не удалось удалить транзакцию',
    deleteTransaction: 'Удалить транзакцию',
    deleteTransactionConfirmation: 'Вы уверены, что хотите удалить эту транзакцию? Это действие нельзя отменить.',
    budgetCreatedSuccessfully: 'Бюджет успешно создан!',
    budgetUpdatedSuccessfully: 'Бюджет успешно обновлен!',
    budgetDeletedSuccessfully: 'Бюджет успешно удален!',
    failedToCreateBudget: 'Не удалось создать бюджет',
    failedToUpdateBudget: 'Не удалось обновить бюджет',
    failedToDeleteBudget: 'Не удалось удалить бюджет',
    categoryCreatedSuccessfully: 'Категория успешно создана!',
    categoryDeletedSuccessfully: 'Категория успешно удалена!',
    failedToCreateCategory: 'Не удалось создать категорию',
    failedToDeleteCategory: 'Не удалось удалить категорию',
    pleaseFillAllFields: 'Пожалуйста, заполните все поля',
    last4DigitsMustBe4: 'Последние 4 цифры должны состоять ровно из 4 цифр',
    
    // Expenses
    incomeExpenseTracking: 'Учет доходов и расходов',
    manageYourFinances: 'Управляйте финансами и отслеживайте расходы',
    addTransaction: 'Добавить транзакцию',
    totalIncome: 'Общий доход',
    totalExpenses: 'Общие расходы',
    netAmount: 'Чистая сумма',
    net: 'Чистая',
    expensesByCategory: 'Расходы по категориям',
    expensesByPaymentMethod: 'Расходы по способу оплаты',
    noPaymentMethodData: 'Нет данных о способах оплаты',
    noDataAvailable: 'Нет данных',
    noPositionsYet: 'Позиций пока нет',
    monthlyTrend: 'Месячный тренд',
    monthlyTrendLast6: 'Месячный тренд (последние 6 месяцев)',
    noTransactionsYet: 'Транзакций пока нет',
    startTrackingFinances: 'Начните отслеживать свои финансы, добавив первую транзакцию',
    trackYourIncomeExpenses: 'Отслеживайте доходы и расходы',
    incomeThisMonth: 'Доход (В этом месяце)',
    expensesThisMonth: 'Расходы (В этом месяце)',
    transactions: 'Транзакции',
    searchTransactions: 'Поиск транзакций...',
    noExpenseData: 'Нет данных о расходах',
    income: 'Доход',
    expense: 'Расход',

    // Transaction Dialog
    editTransaction: 'Редактировать транзакцию',
    duplicateTransaction: 'Дублировать транзакцию',
    duplicateTransactionDescription: 'Создать копию этой транзакции с сегодняшней датой',
    addTransactionTitle: 'Добавить транзакцию',
    updateTransactionDetails: 'Обновить данные транзакции',
    recordNewTransaction: 'Записать новую транзакцию дохода или расхода',
    date: 'Дата',
    type: 'Тип',
    category: 'Категория',
    description: 'Описание',
    amount: 'Сумма',
    currency: 'Валюта',
    relatedAccount: 'Связанный счет (необязательно)',
    selectAccountOptional: 'Выберите счет (необязательно)',
    none: 'Нет',
    linkTransactionToAccount: 'Привязать эту транзакцию к инвестиционному счету, если применимо',
    updateTransaction: 'Обновить транзакцию',
    dateRequired: 'Дата обязательна',
    descriptionRequired: 'Описание обязательно',
    amountGreaterThanZero: 'Сумма должна быть больше 0',
    descriptionPlaceholder: 'Например: Покупка продуктов',

    // Transaction Filters
    filters: 'Фильтры',
    clear: 'Очистить',
    last7Days: 'Последние 7 дней',
    allTime: 'Все время',
    fromDate: 'С даты',
    toDate: 'По дату',
    allTypes: 'Все типы',
    expensesOnly: 'Только расходы',
    incomeOnly: 'Только доходы',
    allCategories: 'Все категории',

    // Transaction List
    noTransactionsFound: 'Транзакции не найдены',
    addFirstTransactionOrAdjust: 'Добавьте первую транзакцию или измените фильтры',

    // Categories
    foodDining: 'Еда и рестораны',
    groceries: 'Продукты',
    rentHousing: 'Аренда и жилье',
    transportation: 'Транспорт',
    healthcare: 'Здравоохранение',
    entertainment: 'Развлечения',
    shopping: 'Покупки',
    utilities: 'Коммунальные услуги',
    insurance: 'Страхование',
    investmentFees: 'Инвестиционные сборы',
    taxes: 'Налоги',
    salary: 'Зарплата',
    investmentIncome: 'Инвестиционный доход',
    other: 'Другое',
    
    // Category Manager
    manageCategories: 'Управление категориями',
    addManageCategoriesDesc: 'Добавить и управлять категориями транзакций',
    categoryName: 'Название категории',
    categoryPlaceholder: 'напр., Подписка, Подарки',
    addCategory: 'Добавить категорию',
    categoryNameRequired: 'Название категории обязательно',
    categoryExists: 'Категория уже существует',
    noCategoriesYet: 'Категорий пока нет. Добавьте первую категорию выше.',
    both: 'Оба',
    
    // Settings
    manageAccountPreferences: 'Управление аккаунтом и настройками',
    profileInformation: 'Информация профиля',
    fullName: 'Полное имя',
    email: 'Email',
    role: 'Роль',
    fullNameUpdated: 'Полное имя успешно обновлено',
    failedToUpdateFullName: 'Не удалось обновить полное имя',
    preferences: 'Настройки',
    language: 'Язык',
    displayLanguage: 'Язык отображения',
    defaultCurrency: 'Валюта по умолчанию',
    primaryCurrencyForPortfolio: 'Основная валюта портфеля',
    theme: 'Тема',
    appColorScheme: 'Цветовая схема',
    dark: 'Темная',
    light: 'Светлая',
    privacy: 'Конфиденциальность',
    blurFinancialValues: 'Размыть финансовые значения',
    hideAmountsWhenShowing: 'Скрыть суммы при показе другим (режим конфиденциальности)',
    notifications: 'Уведомления',
    priceAlerts: 'Оповещения о ценах',
    getNotifiedPriceChanges: 'Получать уведомления о значительных изменениях цен',
    dailySummary: 'Ежедневная сводка',
    receiveDailyReports: 'Получать ежедневные отчеты о портфеле',
    weeklySummary: 'Еженедельная сводка',
    receiveWeeklyReports: 'Получать еженедельные отчеты о портфеле',
    emailNotifications: 'Email уведомления',
    exportedSuccessfully: 'успешно экспортировано',
    exportFailed: 'Не удалось экспортировать данные',
    receiveImportantUpdates: 'Получать важные обновления по email',
    sharedAccess: 'Совместный доступ',
    inviteUser: 'Пригласить пользователя',
    noSharedUsersYet: 'Совместных пользователей пока нет',
    inviteFirstUser: 'Пригласить первого пользователя',
    importExport: 'Импорт / Экспорт',
    paymentCards: 'Платежные карты',
    addCard: 'Добавить карту',
    noCardsYet: 'Карты еще не добавлены',
    cardName: 'Название карты',
    lastFourDigits: 'Последние 4 цифры',
    cardType: 'Тип карты',
    credit: 'Кредитная',
    debit: 'Дебетовая',

    // Account Detail
    backToPortfolio: 'Вернуться к портфелю',
    refreshPrices: 'Обновить цены',
    addPosition: 'Добавить позицию',
    allocation: 'Распределение',
    topHoldings: 'Топ активов',
    positionValue: 'Стоимость позиции',
    selectPosition: 'Выберите позицию',
    selectPositionToView: 'Выберите позицию для просмотра графика',
    positions: 'Позиции',
    noPositionsYetAddFirst: 'Позиций пока нет. Добавьте первую позицию',
    accountNotFound: 'Счет не найден',
    currentPrice: 'Текущая цена',

    // Add Account Dialog
    addNewAccount: 'Добавить новый счет',
    createNewInvestmentAccount: 'Создайте новый инвестиционный счет для отслеживания портфеля',
    accountName: 'Название счета',
    accountNamePlaceholder: 'Например: Interactive Brokers',
    accountType: 'Тип счета',
    initialInvestment: 'Начальная инвестиция',
    notesOptional: 'Заметки (необязательно)',
    notesPlaceholder: 'Добавьте заметки об этом счете...',
    deductFromCash: 'Списать с баланса наличных',
    availableCash: 'Доступные наличные',
    purchaseCost: 'Стоимость покупки',
    remainingCash: 'Остаток',
    insufficientCash: 'Недостаточно наличных для этой покупки',
    cashReturned: 'Наличные возвращены на счет',
    cashAdded: 'Наличные добавлены к существующему балансу!',
    addToCash: 'Сумма для добавления',
    cashWillBeAdded: 'Это будет добавлено к вашему существующему балансу наличных',
    createAccount: 'Создать счет',
    creating: 'Создание...',

    // Add Position Dialog
    addNewPosition: 'Добавить новую позицию',
    editPosition: 'Редактировать позицию',
    updatePositionDetails: 'Обновить данные позиции',
    addNewStockEtf: 'Добавьте акцию, ETF или другой актив на ваш счет',
    symbol: 'Символ',
    symbolPlaceholder: 'Например: AAPL',
    quantity: 'Количество',
    avgPrice: 'Средняя цена',
    addPositionBtn: 'Добавить позицию',
    updatePositionBtn: 'Обновить позицию',
    sellPosition: 'Продать позицию',
    sellPositionDescription: 'Продажа из вашего портфеля',
    position: 'Позиция',
    currentValue: 'Текущая стоимость',
    justDelete: 'Просто удалить',
    sellAndReturnCash: 'Продать и вернуть в наличные',
    currentHolding: 'Текущие активы',
    quantityToSell: 'Количество для продажи',
    sellAll: 'Продать всё',
    sellPrice: 'Цена продажи за единицу',
    saleSummary: 'Сводка продажи',
    totalProceeds: 'Общая выручка',
    costBasis: 'Базовая стоимость',
    profitLoss: 'Прибыль/Убыток',
    remaining: 'Остаток',
    addProceedsToCash: 'Добавить выручку к балансу наличных',
    sellNotesPlaceholder: 'Причина продажи, рыночные условия и т.д.',
    selling: 'Продажа...',
    sellPartial: 'Продать',
    invalidQuantity: 'Недопустимое количество',
    depositRecorded: 'Депозит наличных записан!',
    buyRecorded: 'Позиция куплена!',
    sellRecorded: 'Позиция продана!',
    positionDeleted: 'Позиция удалена!',
    depositAmount: 'Сумма депозита',
    currentCashBalance: 'Текущий баланс наличных',
    depositTrackedSeparately: 'Каждый депозит записывается как отдельная транзакция',
    transactionHistory: 'История транзакций',
    buy: 'Покупка',
    sell: 'Продажа',
    deposit: 'Депозит',
    withdrawal: 'Снятие',
    noPortfolioTransactionsYet: 'Транзакций пока нет',
    transactionsWillAppear: 'Транзакции покупки, продажи и депозита появятся здесь',
    price: 'Цена',
    total: 'Всего',

    // Dashboard Customization
    customizeDashboard: 'Настроить панель',
    resetToDefault: 'Сбросить по умолчанию',
    saveLayout: 'Сохранить макет',

    // Widgets
    portfolioValueTrendTitle: 'Тренд стоимости портфеля',
    historicalPortfolioPerformance: 'Исторические показатели портфеля',
    netWorthChart: 'График чистой стоимости',
    assetsMinus: 'Активы минус накопительные расходы',
    accountAllocationTitle: 'Распределение по счетам',
    breakdownByAccountType: 'Разбивка по типу счета',
    assetAllocationTitle: 'Распределение активов',
    distributionByAssetType: 'Распределение по типу актива',
    accountSummaryTitle: 'Сводка счетов',
    listOfAllAccounts: 'Список всех счетов',
    savingsRateTitle: 'Норма сбережений',
    monthlySavingsPercentage: 'Процент ежемесячных сбережений',
    benchmarkComparisonTitle: 'Сравнение с бенчмарком',
    performanceVsSP500Title: 'Производительность vs S&P 500',
    financialGoalsTitle: 'Финансовые цели',
    trackYourFinancialObjectives: 'Отслеживайте свои финансовые цели',

    // Goal Dialog
    addFinancialGoal: 'Добавить финансовую цель',
    editFinancialGoal: 'Редактировать финансовую цель',
    setAndTrackObjectives: 'Установите и отслеживайте финансовые цели',
    goalTitle: 'Название цели',
    goalTitlePlaceholder: 'Например: Пенсионный фонд, Резервный фонд',
    targetAmount: 'Целевая сумма',
    currentAmountGoal: 'Текущая сумма',
    targetDate: 'Целевая дата',
    expectedAnnualReturn: 'Ожидаемая годовая доходность (%)',
    expectedReturnHelp: 'Используется для расчета прогнозируемой даты достижения',
    linkInvestmentAccounts: 'Связать инвестиционные счета (необязательно)',
    progressWillTrack: 'Прогресс будет отслеживаться автоматически на основе связанных счетов',
    addGoalBtn: 'Добавить цель',
    updateGoal: 'Обновить цель',

    // Import/Export
    importExportData: 'Импорт и экспорт данных',
    importData: 'Импорт данных',
    exportData: 'Экспорт данных',
    importType: 'Тип импорта',
    selectCsvFile: 'Выберите CSV файл',
    accounts: 'Счета',
    exportAll: 'Экспортировать все',
    downloadDataCsv: 'Скачайте ваши данные в виде CSV файлов для резервного копирования или анализа.',
    uploadCsvFormats: 'Загрузите CSV файлы в следующих форматах:',

    // Shared Users
    viewPortfolio: 'Просмотр портфеля',
    editPortfolio: 'Редактирование портфеля',
    viewExpenses: 'Просмотр расходов',
    editExpenses: 'Редактирование расходов',
    viewNotes: 'Просмотр заметок',
    editNotes: 'Редактирование заметок',
    viewGoals: 'Просмотр целей',
    editGoals: 'Редактирование целей',
    viewBudgets: 'Просмотр бюджетов',
    editBudgets: 'Редактирование бюджетов',
    viewSettings: 'Просмотр настроек',
    manageUsers: 'Управление пользователями',
    canSeeAccountsPositions: 'Может видеть счета и позиции',
    canAddEditAccountsPositions: 'Может добавлять/редактировать счета и позиции',
    canSeeExpenseTransactions: 'Может видеть транзакции расходов',
    canAddEditExpenseTransactions: 'Может добавлять/редактировать транзакции расходов',
    canSeeNotes: 'Может видеть заметки и личные мемо',
    canAddEditNotes: 'Может создавать, редактировать и удалять заметки',
    canSeeFinancialGoals: 'Может видеть финансовые цели и прогресс',
    canAddEditFinancialGoals: 'Может создавать, редактировать и удалять финансовые цели',
    canSeeBudgets: 'Может видеть категории бюджета и лимиты',
    canAddEditBudgets: 'Может создавать, редактировать и удалять бюджеты',
    canAccessSettingsPage: 'Может получить доступ к странице настроек',
    canInviteManageUsers: 'Может приглашать и управлять пользователями',
    emailAddress: 'Email адрес',
    displayName: 'Отображаемое имя',
    permissions: 'Разрешения',
    sendInvitation: 'Отправить приглашение',
    sending: 'Отправка...',
    pending: 'ожидание',
    accepted: 'принят',
    revoked: 'отозван',
    
    // Budget
    budgetTracking: 'Отслеживание бюджета',
    manageBudgets: 'Управление бюджетами',
    setBudgetLimits: 'Установите ежемесячные лимиты расходов для разных категорий',
    allCategoriesHaveBudgets: 'У всех категорий есть бюджеты',
    deleteBudgetToAddNew: 'Удалите существующий бюджет, чтобы добавить новый, или отредактируйте существующие бюджеты ниже.',
    monthlyLimit: 'Месячный лимит',
    alertThreshold: 'Порог предупреждения',
    alertThresholdHelp: 'Вы получите уведомление, когда расходы достигнут этого процента',
    updateBudget: 'Обновить бюджет',
    addBudget: 'Добавить бюджет',
    currentBudgets: 'Текущие бюджеты',
    overBudgetBy: 'Превышение бюджета на',
    reachedLimit: 'Лимит достигнут',
    approachingLimit: 'Приближение к лимиту',
    perMonth: '/месяц',
    alertAt: 'Оповещение при',
    selectCategory: 'Выберите категорию',
    
    // Period Selector
    year: 'Год',
    currentMonth: 'Текущий месяц',
    clickToChangePeriod: 'Нажмите для изменения периода',
    futureMonth: 'Будущий месяц',
    noTransactions: 'Нет транзакций',
    yearlyView: 'Годовой вид',
    months: 'месяцев',
    all: 'Все',
    
    // Expense View
    cardPayments: 'Платежи картой',
    cashPayments: 'Платежи наличными',
    showing: 'Показано',
    of: 'из',
    
    // Months
    january: 'Январь',
    february: 'Февраль',
    march: 'Март',
    april: 'Апрель',
    may: 'Май',
    june: 'Июнь',
    july: 'Июль',
    august: 'Август',
    september: 'Сентябрь',
    october: 'Октябрь',
    november: 'Ноябрь',
    december: 'Декабрь',
    jan: 'Янв',
    feb: 'Фев',
    mar: 'Мар',
    apr: 'Апр',
    jun: 'Июн',
    jul: 'Июл',
    aug: 'Авг',
    sep: 'Сен',
    oct: 'Окт',
    nov: 'Ноя',
    dec: 'Дек',
  },
};

// Public routes that don't require authentication
const PUBLIC_ROUTES = ['/login', '/privacy-policy', '/terms-of-service', '/accept-invitation'];

const isPublicRoute = (pathname) => {
  return PUBLIC_ROUTES.some(route => {
    if (route.includes(':')) {
      // Handle dynamic routes like /accept-invitation/:token
      const routePattern = route.replace(/:[^/]+/g, '[^/]+');
      const regex = new RegExp(`^${routePattern}`);
      return regex.test(pathname);
    }
    return pathname.startsWith(route);
  });
};

export function ThemeProvider({ children }) {
  const [user, setUser] = useState(null);
  const [loading, setLoading] = useState(true);

  const loadUser = useCallback(async () => {
    // Skip auth check on public routes
    const pathname = window.location.pathname;
    if (isPublicRoute(pathname)) {
      setLoading(false);
      return null;
    }

    try {
      const currentUser = await ascent.auth.me();
      setUser(currentUser);
      return currentUser;
    } catch (error) {
      // Silently fail on public routes or 401 errors
      if (isPublicRoute(pathname) || error.status === 401 || error.status === 403) {
        return null;
      }
      console.error('Failed to load user');
      return null;
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadUser();
  }, [loadUser]);

  // Function to refresh user data (called after settings update)
  const refreshUser = useCallback(async () => {
    const updatedUser = await loadUser();
    return updatedUser;
  }, [loadUser]);

  // Function to update user locally (for instant UI feedback)
  const updateUserLocal = useCallback((updates) => {
    setUser(prev => prev ? { ...prev, ...updates } : null);
  }, []);

  const theme = user?.theme || 'dark';
  const language = user?.language || 'en';
  const isRTL = language === 'he';

  const t = useCallback((key) => translations[language]?.[key] || translations.en[key] || key, [language]);

  const colors = React.useMemo(() => theme === 'light' ? {
    bgPrimary: 'bg-slate-50',
    bgSecondary: 'bg-white',
    bgTertiary: 'bg-slate-100',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-700',
    textTertiary: 'text-slate-500',
    border: 'border-slate-200',
    borderLight: 'border-slate-100',
    accent: 'bg-[#5C8374]',
    accentHover: 'hover:bg-[#4a6b5e]',
    accentText: 'text-[#5C8374]',
    cardBg: 'bg-white',
    cardBorder: 'border-slate-200',
  } : {
    bgPrimary: 'bg-[#092635]',
    bgSecondary: 'bg-[#1B4242]',
    bgTertiary: 'bg-[#092635]',
    textPrimary: 'text-white',
    textSecondary: 'text-[#9EC8B9]',
    textTertiary: 'text-[#9EC8B9]/70',
    border: 'border-[#5C8374]/20',
    borderLight: 'border-[#5C8374]/10',
    accent: 'bg-[#5C8374]',
    accentHover: 'hover:bg-[#5C8374]/80',
    accentText: 'text-[#9EC8B9]',
    cardBg: 'bg-[#1B4242]',
    cardBorder: 'border-[#5C8374]/20',
  }, [theme]);

  const value = React.useMemo(() => ({
    user,
    setUser,
    theme,
    language,
    isRTL,
    colors,
    t,
    loading,
    refreshUser,
    updateUserLocal,
  }), [user, theme, language, isRTL, colors, t, loading, refreshUser, updateUserLocal]);

  return (
    <ThemeContext.Provider value={value}>
      {children}
    </ThemeContext.Provider>
  );
}

export function useTheme() {
  const context = useContext(ThemeContext);
  if (!context) {
    throw new Error('useTheme must be used within ThemeProvider');
  }
  return context;
}

export function translateCategory(categoryNameOrKey, language = 'en') {
  // Translation keys (used by default categories from API)
  const keyMap = {
    // Expense categories
    'food_dining': { en: 'Food & Dining', he: 'אוכל ומסעדות', ru: 'Еда и рестораны' },
    'groceries': { en: 'Groceries', he: 'מכולת', ru: 'Продукты' },
    'transportation': { en: 'Transportation', he: 'תחבורה', ru: 'Транспорт' },
    'utilities': { en: 'Utilities', he: 'חשבונות שוטפים', ru: 'Коммунальные услуги' },
    'rent_housing': { en: 'Rent & Housing', he: 'שכירות ודיור', ru: 'Аренда и жилье' },
    'healthcare': { en: 'Healthcare', he: 'בריאות', ru: 'Здравоохранение' },
    'entertainment': { en: 'Entertainment', he: 'בידור', ru: 'Развлечения' },
    'shopping': { en: 'Shopping', he: 'קניות', ru: 'Покупки' },
    'insurance': { en: 'Insurance', he: 'ביטוח', ru: 'Страхование' },
    'education': { en: 'Education', he: 'חינוך', ru: 'Образование' },
    'personal_care': { en: 'Personal Care', he: 'טיפוח אישי', ru: 'Личный уход' },
    'subscriptions': { en: 'Subscriptions', he: 'מנויים', ru: 'Подписки' },
    'travel': { en: 'Travel', he: 'נסיעות', ru: 'Путешествия' },
    'gifts': { en: 'Gifts', he: 'מתנות', ru: 'Подарки' },
    'taxes': { en: 'Taxes', he: 'מיסים', ru: 'Налоги' },
    'other_expense': { en: 'Other', he: 'אחר', ru: 'Другое' },
    // Income categories
    'salary': { en: 'Salary', he: 'משכורת', ru: 'Зарплата' },
    'freelance': { en: 'Freelance', he: 'פרילנס', ru: 'Фриланс' },
    'investments': { en: 'Investment Income', he: 'הכנסות מהשקעות', ru: 'Инвестиционный доход' },
    'rental_income': { en: 'Rental Income', he: 'הכנסות משכירות', ru: 'Доход от аренды' },
    'gifts_received': { en: 'Gifts Received', he: 'מתנות שהתקבלו', ru: 'Полученные подарки' },
    'refunds': { en: 'Refunds', he: 'החזרים', ru: 'Возвраты' },
    'other_income': { en: 'Other Income', he: 'הכנסה אחרת', ru: 'Другой доход' },
    // Legacy name mappings for backwards compatibility
    'Food & Dining': { en: 'Food & Dining', he: 'אוכל ומסעדות', ru: 'Еда и рестораны' },
    'Groceries': { en: 'Groceries', he: 'מכולת', ru: 'Продукты' },
    'Rent & Housing': { en: 'Rent & Housing', he: 'שכירות ודיור', ru: 'Аренда и жилье' },
    'Transportation': { en: 'Transportation', he: 'תחבורה', ru: 'Транспорт' },
    'Healthcare': { en: 'Healthcare', he: 'בריאות', ru: 'Здравоохранение' },
    'Entertainment': { en: 'Entertainment', he: 'בידור', ru: 'Развлечения' },
    'Shopping': { en: 'Shopping', he: 'קניות', ru: 'Покупки' },
    'Utilities': { en: 'Utilities', he: 'חשבונות', ru: 'Коммунальные услуги' },
    'Insurance': { en: 'Insurance', he: 'ביטוח', ru: 'Страхование' },
    'Investment Fees': { en: 'Investment Fees', he: 'עמלות השקעה', ru: 'Инвестиционные сборы' },
    'Taxes': { en: 'Taxes', he: 'מיסים', ru: 'Налоги' },
    'Salary': { en: 'Salary', he: 'משכורת', ru: 'Зарплата' },
    'Investment Income': { en: 'Investment Income', he: 'הכנסות מהשקעות', ru: 'Инвестиционный доход' },
    'Other': { en: 'Other', he: 'אחר', ru: 'Другое' }
  };
  return keyMap[categoryNameOrKey]?.[language] || categoryNameOrKey;
}
